### ISSUE TITLE
Documenting how we handle versioning

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/community-translations-standard#9]
We should write down in the README how we want to handle versioning of the translations (that is, how do we show/know which version is translated).

**Comment by Ainali** [comment]
Besides the process of tagging, we could have a section similar to this mockup below:

## Available versions

| language | version | 
|-|-|
| da | 0.2.1 |
| es | 0.2.1 |

**Comment by ericherman** [comment]
Yes, as they are community translations, they may not stay in synch, yet should be clear about what version they are -- the table you present does this.
